spring:
  datasource:
    username: root
    password: Zxc3250033
    url: jdbc:mysql://47.115.25.100:3306/gowhere_airline_airbus?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml