#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#      routes:
#        - id: gowhere-airline-boeing
#          uri: lb://gowhere-airline-boeing
#          predicates:
#            - Path=/boeing/**
#          filters:
#            - StripPrefix=1
