spring:
  datasource:
    username: root
    password: Zxc3250033
    url: jdbc:mysql://47.115.25.100:3306/gowhere_pay_alibaba?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: SELECT 1
  rabbitmq:
    host: 47.115.25.100
    port: 5672
    virtual-host: /
  redis:
    host: 47.115.25.100
  cache:
    type: redis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
